id = "sysml-v2"
name = "SysML v2"
description = "SysML v2 language support for Zed via the Spec42 language server."
version = "0.45.0"
schema_version = 1
authors = ["Elan8"]
repository = "https://github.com/elan8/spec42"

[grammars.sysml]
repository = "https://gitlab.com/nomograph/tree-sitter-sysml"
rev = "2376b6ebe4955b3430ea0aeeb01f1bbd67cdc0bd"

[language_servers.spec42]
name = "spec42"
languages = ["SysML v2"]
