//! Sandboxed runtime for Spec42 core WebAssembly generator modules.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use generator_api::{
    ArtifactLimits, ArtifactSet, ElementDetail as ApiElementDetail,
    ElementSummary as ApiElementSummary, GeneratorDiagnostic, GeneratorDiagnosticLevel,
    GeneratorModelView, MultiplicitySummary as ApiMultiplicity, RelationshipSummary,
    RequirementUsageTypingSummary, SatisfyEndpointSummary, SatisfyPolaritySummary,
    SatisfyRelationshipSummary, TypingProvenanceSummary, MAX_ARTIFACT_PATH_BYTES,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use spec42_generator_protocol as protocol;
use thiserror::Error;
use wasmparser::Parser;

mod epoch;

pub use epoch::{Clock, EntryObserver, EpochController, ManualClock, SystemClock};
use epoch::{Deadline, Expiry, TICK_INTERVAL};
use wasmtime::{
    Caller, Config, Engine, Extern, ExternType, Linker, Memory, Module, ResourceLimiter, Store,
    StoreLimits, StoreLimitsBuilder, Trap, UpdateDeadline, ValType,
};

pub const GENERATOR_ABI_VERSION: u32 = protocol::ABI_VERSION;
const MAX_QUERY_TRANSFER_BYTES: usize = 64 * 1024 * 1024;
const MAX_POSTCARD_ARTIFACT_OVERHEAD_BYTES: usize = 20;
const MAX_POSTCARD_RESULT_OVERHEAD_BYTES: usize = 16;
/// Floor for the accepted result size, so a generator's error string is never rejected for
/// being larger than a tiny configured artifact budget. Not a cap — see [`bounded_message`].
const MIN_ACCEPTED_RESULT_BYTES: usize = 64 * 1024;
const MAX_DIAGNOSTICS: usize = 10_000;
const MAX_DIAGNOSTIC_TOTAL_BYTES: usize = 4 * 1024 * 1024;

/// Engine-level configuration for the generator sandbox.
///
/// Generators are build tooling: the user chose the module and invoked it, the same way
/// they invoke a compiler plugin or a build script. The defaults reflect that trust. The
/// controls that remain exist to contain *accidents* — a runaway allocation — and to keep
/// generated bytes reproducible across machines, not to contain an adversary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct RuntimeOptions {
    /// Meter guest instructions, so `fuel_consumed` is reported and [`RuntimeLimits::fuel`]
    /// can be enforced.
    ///
    /// Off by default. Fuel metering instruments every basic block, so it is a cost paid
    /// only when something wants the number — the conformance harness uses it as an exact,
    /// reproducible cost metric, which is the primary reason it still exists.
    pub fuel_metering: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RuntimeLimits {
    /// Ceiling on guest linear memory. Contains a runaway allocation; always applied.
    pub memory_bytes: usize,
    /// Instruction budget. `None` runs unmetered, and requires
    /// [`RuntimeOptions::fuel_metering`] when set.
    pub fuel: Option<u64>,
    /// Wall-clock budget. `None` lets a slow generator take as long as it needs.
    pub wall_time: Option<Duration>,
}

impl Default for RuntimeLimits {
    fn default() -> Self {
        Self {
            memory_bytes: 256 * 1024 * 1024,
            fuel: None,
            wall_time: None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GeneratorFailureCategory {
    ArtifactInvalid,
    ApiIncompatible,
    GeneratorError,
    Trap,
    ResourceExhausted,
    Cancelled,
    OutputPolicy,
}

/// Where a failure happened. An enum rather than a string because these values reach the
/// user through the JSON report and are matched on by the conformance suite, so a typo or a
/// silently renamed stage should be a compile error.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GenerationPhase {
    RuntimeConfiguration,
    ModuleValidation,
    ModuleCompilation,
    ApiCompatibility,
    ApiLinking,
    ResourceConfiguration,
    BeforeExecution,
    GuestInstantiation,
    GuestExecution,
    ArtifactValidation,
}

impl std::fmt::Display for GenerationPhase {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Self::RuntimeConfiguration => "runtime-configuration",
            Self::ModuleValidation => "module-validation",
            Self::ModuleCompilation => "module-compilation",
            Self::ApiCompatibility => "api-compatibility",
            Self::ApiLinking => "api-linking",
            Self::ResourceConfiguration => "resource-configuration",
            Self::BeforeExecution => "before-execution",
            Self::GuestInstantiation => "guest-instantiation",
            Self::GuestExecution => "guest-execution",
            Self::ArtifactValidation => "artifact-validation",
        };
        formatter.write_str(name)
    }
}

/// Raised from a host call to unwind a run that must stop.
///
/// A distinct type so classification does not depend on message text.
#[derive(Debug, Clone, Copy, Error)]
enum GuestInterrupt {
    #[error("generation was cancelled")]
    Cancelled,
    #[error("generation exceeded its wall-clock budget")]
    DeadlineExceeded,
}

/// A guest that broke the ABI contract: a bad pointer, an unknown operation, a malformed
/// payload. Distinct from a trap, because the module is incompatible rather than buggy, and
/// the message names precisely what the guest got wrong.
#[derive(Debug, Error)]
#[error("{0}")]
struct AbiViolation(String);

impl AbiViolation {
    fn error(message: impl Into<String>) -> wasmtime::Error {
        wasmtime::Error::new(Self(message.into()))
    }
}

#[derive(Debug, Error)]
#[error("{category:?} during {phase}: {message}")]
pub struct GeneratorHostError {
    pub category: GeneratorFailureCategory,
    pub phase: GenerationPhase,
    pub message: String,
}

#[derive(Debug)]
pub struct GeneratorExecution {
    pub artifacts: ArtifactSet,
    pub diagnostics: Vec<GeneratorDiagnostic>,
    pub generator_digest: String,
    pub duration: Duration,
    pub query_count: u64,
    /// `None` when the runtime was built without fuel metering.
    pub fuel_consumed: Option<u64>,
    /// High-water mark of guest linear memory.
    pub peak_memory_bytes: usize,
}

#[derive(Debug, Clone)]
pub struct CancellationHandle(Arc<AtomicBool>);

impl CancellationHandle {
    pub fn new() -> Self {
        Self(Arc::new(AtomicBool::new(false)))
    }

    pub fn cancel(&self) {
        self.0.store(true, Ordering::Release);
    }

    pub fn is_cancelled(&self) -> bool {
        self.0.load(Ordering::Acquire)
    }

    /// The shared flag, for a store's epoch callback to observe directly.
    pub(crate) fn flag(&self) -> Arc<AtomicBool> {
        Arc::clone(&self.0)
    }
}

impl Default for CancellationHandle {
    fn default() -> Self {
        Self::new()
    }
}

pub struct GeneratorRuntime {
    engine: Engine,
    options: RuntimeOptions,
    clock: Arc<dyn Clock>,
    /// One ticker for the whole runtime. Dropped with it, which stops the thread.
    _epoch: EpochController,
}

#[derive(Debug)]
pub struct PreparedGenerator {
    module: Module,
    generator_digest: String,
}

impl GeneratorRuntime {
    pub fn new() -> Result<Self, GeneratorHostError> {
        Self::with_options(RuntimeOptions::default())
    }

    pub fn with_options(options: RuntimeOptions) -> Result<Self, GeneratorHostError> {
        Self::with_options_and_clock(options, Arc::new(SystemClock), TICK_INTERVAL)
    }

    /// Builds a runtime with an injected clock and tick cadence.
    ///
    /// Tests supply a [`ManualClock`] and a long interval, then drive expiry by advancing the
    /// clock and ticking explicitly, so no test depends on sleeping or on the scheduler.
    pub fn with_options_and_clock(
        options: RuntimeOptions,
        clock: Arc<dyn Clock>,
        tick_interval: Duration,
    ) -> Result<Self, GeneratorHostError> {
        let mut config = Config::new();
        config.consume_fuel(options.fuel_metering);
        // Kept on unconditionally: it is how a cancelled or timed-out run interrupts guest
        // code. Guest execution that never crosses a loop back-edge or function entry is
        // interrupted by the host-call checks in `HostState::guard` instead.
        config.epoch_interruption(true);
        config.max_wasm_stack(2 * 1024 * 1024);
        // Determinism. Generated artifacts are compared byte-for-byte by `--check`, so the
        // engine must not be a source of variation between machines. Relaxed SIMD exists
        // precisely to let results differ per architecture, and NaN bit patterns are
        // otherwise platform-dependent; both are pinned here.
        config.relaxed_simd_deterministic(true);
        config.cranelift_nan_canonicalization(true);
        let engine = Engine::new(&config).map_err(|error| GeneratorHostError {
            category: GeneratorFailureCategory::ArtifactInvalid,
            phase: GenerationPhase::RuntimeConfiguration,
            message: error.to_string(),
        })?;
        let epoch = EpochController::spawn(&engine, tick_interval);
        Ok(Self {
            engine,
            options,
            clock,
            _epoch: epoch,
        })
    }

    pub fn options(&self) -> RuntimeOptions {
        self.options
    }

    /// Advances the engine epoch once.
    ///
    /// Exists so deterministic tests can drive expiry themselves: pair it with a
    /// [`ManualClock`] and a long tick interval and no test needs to sleep or guess at
    /// scheduling. Production ticking is the runtime's own [`EpochController`].
    pub fn tick_epoch(&self) {
        self.engine.increment_epoch();
    }

    pub fn execute(
        &self,
        module_bytes: &[u8],
        model: Arc<GeneratorModelView>,
        args: &[String],
        runtime_limits: RuntimeLimits,
        artifact_limits: ArtifactLimits,
        cancellation: CancellationHandle,
    ) -> Result<GeneratorExecution, GeneratorHostError> {
        let prepared = self.prepare(module_bytes)?;
        self.execute_prepared(
            &prepared,
            model,
            args,
            runtime_limits,
            artifact_limits,
            cancellation,
        )
    }

    /// Validates and compiles a core module without loading a model snapshot.
    pub fn prepare(&self, module_bytes: &[u8]) -> Result<PreparedGenerator, GeneratorHostError> {
        let generator_digest = digest(module_bytes);
        if !Parser::is_core_wasm(module_bytes) {
            return Err(GeneratorHostError {
                category: GeneratorFailureCategory::ArtifactInvalid,
                phase: GenerationPhase::ModuleValidation,
                message: "not a core WebAssembly module".to_owned(),
            });
        }

        let module =
            Module::new(&self.engine, module_bytes).map_err(|error| GeneratorHostError {
                category: GeneratorFailureCategory::ArtifactInvalid,
                phase: GenerationPhase::ModuleCompilation,
                message: format!("failed to compile WebAssembly module: {error}"),
            })?;
        validate_module_exports(&module).map_err(|message| GeneratorHostError {
            category: GeneratorFailureCategory::ApiIncompatible,
            phase: GenerationPhase::ApiCompatibility,
            message,
        })?;
        let mut linker = Linker::<HostState>::new(&self.engine);
        add_host_functions(&mut linker).map_err(|error| GeneratorHostError {
            category: GeneratorFailureCategory::ApiIncompatible,
            phase: GenerationPhase::ApiLinking,
            message: error.to_string(),
        })?;
        linker
            .instantiate_pre(&module)
            .map_err(|error| GeneratorHostError {
                category: GeneratorFailureCategory::ApiIncompatible,
                phase: GenerationPhase::ApiCompatibility,
                message: format!(
                    "module does not implement the Spec42 generator ABI v{GENERATOR_ABI_VERSION}: {error}"
                ),
            })?;
        Ok(PreparedGenerator {
            module,
            generator_digest,
        })
    }

    /// Runs a prepared module against a model snapshot.
    ///
    /// Safe to call concurrently on one `GeneratorRuntime`. Epoch ticks are engine-global,
    /// but each store's epoch callback decides whether a tick is its own deadline or
    /// cancellation, so an execution that times out does not disturb its siblings.
    pub fn execute_prepared(
        &self,
        prepared: &PreparedGenerator,
        model: Arc<GeneratorModelView>,
        args: &[String],
        runtime_limits: RuntimeLimits,
        artifact_limits: ArtifactLimits,
        cancellation: CancellationHandle,
    ) -> Result<GeneratorExecution, GeneratorHostError> {
        self.execute_prepared_observed(
            prepared,
            model,
            args,
            runtime_limits,
            artifact_limits,
            cancellation,
            &EntryObserver::unobserved(),
        )
    }

    /// As [`Self::execute_prepared`], reporting when the guest first calls into the host.
    ///
    /// Tests use the observer to establish that WebAssembly is actually running before they
    /// cancel or advance the clock. Signalling before `execute` would prove only that a
    /// thread was spawned, which a pre-cancelled handle satisfies without the guest ever
    /// entering.
    #[allow(clippy::too_many_arguments)]
    pub fn execute_prepared_observed(
        &self,
        prepared: &PreparedGenerator,
        model: Arc<GeneratorModelView>,
        args: &[String],
        runtime_limits: RuntimeLimits,
        artifact_limits: ArtifactLimits,
        cancellation: CancellationHandle,
        observer: &EntryObserver,
    ) -> Result<GeneratorExecution, GeneratorHostError> {
        let entered = observer.flag();
        if cancellation.is_cancelled() {
            return Err(GeneratorHostError {
                category: GeneratorFailureCategory::Cancelled,
                phase: GenerationPhase::BeforeExecution,
                message: "generation was cancelled".to_owned(),
            });
        }

        let mut linker = Linker::new(&self.engine);
        add_host_functions(&mut linker).map_err(|error| GeneratorHostError {
            category: GeneratorFailureCategory::ApiIncompatible,
            phase: GenerationPhase::ApiLinking,
            message: error.to_string(),
        })?;
        if runtime_limits.fuel.is_some() && !self.options.fuel_metering {
            return Err(GeneratorHostError {
                category: GeneratorFailureCategory::ResourceExhausted,
                phase: GenerationPhase::ResourceConfiguration,
                message: "a fuel limit requires a runtime built with fuel metering enabled"
                    .to_owned(),
            });
        }

        let mut linker = Linker::new(&self.engine);
        add_host_functions(&mut linker).map_err(|error| GeneratorHostError {
            category: GeneratorFailureCategory::ApiIncompatible,
            phase: GenerationPhase::ApiLinking,
            message: error.to_string(),
        })?;
        let deadline = runtime_limits
            .wall_time
            .and_then(|wall_time| self.clock.now().checked_add(wall_time));
        let mut store = Store::new(
            &self.engine,
            HostState {
                model,
                diagnostics: Vec::new(),
                diagnostic_bytes: 0,
                last_response: None,
                limits: MeteredLimits::new(runtime_limits.memory_bytes),
                query_count: 0,
                deadline,
                clock: Arc::clone(&self.clock),
                cancellation: cancellation.clone(),
                entered: entered.clone(),
            },
        );
        store.limiter(|state| &mut state.limits);
        if let Some(fuel) = runtime_limits.fuel {
            store.set_fuel(fuel).map_err(|error| GeneratorHostError {
                category: GeneratorFailureCategory::ResourceExhausted,
                phase: GenerationPhase::ResourceConfiguration,
                message: error.to_string(),
            })?;
        }
        // Ticks come from the runtime's single ticker and are seen by every store sharing
        // the engine, so each store decides for itself what one means. A tick that is neither
        // this run's cancellation nor its elapsed deadline simply re-arms, which is what
        // makes concurrent executions -- including concurrent deadlines -- independent.
        store.set_epoch_deadline(1);
        let store_deadline = Deadline::new(deadline, cancellation.flag());
        let clock = Arc::clone(&self.clock);
        store.epoch_deadline_callback(move |_| match store_deadline.evaluate(clock.now()) {
            Some(Expiry::Cancelled) => Err(wasmtime::Error::new(GuestInterrupt::Cancelled)),
            Some(Expiry::DeadlineExceeded) => {
                Err(wasmtime::Error::new(GuestInterrupt::DeadlineExceeded))
            }
            None => Ok(UpdateDeadline::Continue(1)),
        });

        let started = Instant::now();
        let guest_result = execute_guest(
            &mut store,
            &linker,
            &prepared.module,
            args,
            artifact_limits,
            &cancellation,
        );
        let artifacts = guest_result?;
        let duration = started.elapsed();
        let fuel_consumed = runtime_limits.fuel.map(|fuel| {
            let remaining = store.get_fuel().unwrap_or(0);
            fuel.saturating_sub(remaining)
        });
        let state = store.into_data();
        Ok(GeneratorExecution {
            artifacts,
            diagnostics: state.diagnostics,
            generator_digest: prepared.generator_digest.clone(),
            duration,
            query_count: state.query_count,
            fuel_consumed,
            peak_memory_bytes: state.limits.peak_memory_bytes,
        })
    }
}

/// [`StoreLimits`] plus a high-water mark for guest linear memory.
///
/// `memory_growing` is called at memory *creation* as well as on `memory.grow`, so the peak
/// covers a guest that reserves everything up front, and it records the requested size even
/// when the growth is refused.
struct MeteredLimits {
    inner: StoreLimits,
    peak_memory_bytes: usize,
}

impl MeteredLimits {
    fn new(memory_bytes: usize) -> Self {
        Self {
            inner: StoreLimitsBuilder::new()
                .memory_size(memory_bytes)
                .instances(10)
                .memories(1)
                .tables(8)
                .table_elements(1_000_000)
                .build(),
            peak_memory_bytes: 0,
        }
    }
}

impl ResourceLimiter for MeteredLimits {
    fn memory_growing(
        &mut self,
        current: usize,
        desired: usize,
        maximum: Option<usize>,
    ) -> wasmtime::Result<bool> {
        self.peak_memory_bytes = self.peak_memory_bytes.max(desired);
        self.inner.memory_growing(current, desired, maximum)
    }

    fn table_growing(
        &mut self,
        current: usize,
        desired: usize,
        maximum: Option<usize>,
    ) -> wasmtime::Result<bool> {
        self.inner.table_growing(current, desired, maximum)
    }

    fn memory_grow_failed(&mut self, error: wasmtime::Error) -> wasmtime::Result<()> {
        self.inner.memory_grow_failed(error)
    }

    fn table_grow_failed(&mut self, error: wasmtime::Error) -> wasmtime::Result<()> {
        self.inner.table_grow_failed(error)
    }

    fn instances(&self) -> usize {
        self.inner.instances()
    }

    fn tables(&self) -> usize {
        self.inner.tables()
    }

    fn memories(&self) -> usize {
        self.inner.memories()
    }
}

fn validate_module_exports(module: &Module) -> Result<(), String> {
    match module.get_export("memory") {
        Some(ExternType::Memory(_)) => {}
        Some(_) => return Err("module export `memory` is not WebAssembly memory".to_owned()),
        None => return Err("module does not export `memory`".to_owned()),
    }

    require_function(module, "spec42_abi_version", &[], &[ValType::I64])?;
    require_function(module, "spec42_alloc", &[ValType::I32], &[ValType::I32])?;
    require_function(
        module,
        "spec42_generate",
        &[ValType::I32, ValType::I32],
        &[ValType::I64],
    )
}

fn require_function(
    module: &Module,
    name: &str,
    expected_params: &[ValType],
    expected_results: &[ValType],
) -> Result<(), String> {
    let function = match module.get_export(name) {
        Some(ExternType::Func(function)) => function,
        Some(_) => return Err(format!("module export `{name}` is not a function")),
        None => return Err(format!("module does not export `{name}`")),
    };
    let params = function.params().collect::<Vec<_>>();
    let results = function.results().collect::<Vec<_>>();
    let params_match = params.len() == expected_params.len()
        && params
            .iter()
            .zip(expected_params)
            .all(|(actual, expected)| actual.matches(expected));
    let results_match = results.len() == expected_results.len()
        && results
            .iter()
            .zip(expected_results)
            .all(|(actual, expected)| actual.matches(expected));
    if !params_match || !results_match {
        return Err(format!(
            "module export `{name}` has an incompatible function signature"
        ));
    }
    Ok(())
}

fn execute_guest(
    store: &mut Store<HostState>,
    linker: &Linker<HostState>,
    module: &Module,
    args: &[String],
    artifact_limits: ArtifactLimits,
    cancellation: &CancellationHandle,
) -> Result<ArtifactSet, GeneratorHostError> {
    let instance = linker.instantiate(&mut *store, module).map_err(|error| {
        classify_wasmtime_error(GenerationPhase::GuestInstantiation, error, cancellation)
    })?;
    let memory = instance.get_memory(&mut *store, "memory").ok_or_else(|| {
        incompatible(
            GenerationPhase::GuestInstantiation,
            "module does not export memory",
        )
    })?;
    let alloc = instance
        .get_typed_func::<i32, i32>(&mut *store, "spec42_alloc")
        .map_err(|error| incompatible(GenerationPhase::GuestInstantiation, error.to_string()))?;
    let generate = instance
        .get_typed_func::<(i32, i32), i64>(&mut *store, "spec42_generate")
        .map_err(|error| incompatible(GenerationPhase::GuestInstantiation, error.to_string()))?;
    let abi_version = instance
        .get_typed_func::<(), i64>(&mut *store, "spec42_abi_version")
        .map_err(|error| incompatible(GenerationPhase::GuestInstantiation, error.to_string()))?;

    // Before anything else, confirm both sides agree on the wire schema. Postcard payloads
    // are positional, so a mismatch here would otherwise surface as plausible-looking but
    // wrongly-offset data rather than an error.
    let reported = abi_version.call(&mut *store, ()).map_err(|error| {
        classify_wasmtime_error(GenerationPhase::GuestInstantiation, error, cancellation)
    })? as u64;
    if reported != protocol::COMPATIBILITY_TOKEN {
        return Err(incompatible(
            GenerationPhase::ApiCompatibility,
            format!(
                "generator was built against an incompatible Spec42 generator ABI \
                 (generator {reported:#018x}, host {:#018x}); rebuild it against ABI v{}",
                protocol::COMPATIBILITY_TOKEN,
                GENERATOR_ABI_VERSION
            ),
        ));
    }

    let args_bytes = postcard::to_allocvec(args).map_err(|error| GeneratorHostError {
        category: GeneratorFailureCategory::GeneratorError,
        phase: GenerationPhase::GuestExecution,
        message: format!("failed to encode generator arguments: {error}"),
    })?;
    let args_len = i32::try_from(args_bytes.len()).map_err(|_| {
        incompatible(
            GenerationPhase::GuestExecution,
            "generator arguments exceed the ABI limit",
        )
    })?;
    let args_ptr = alloc.call(&mut *store, args_len).map_err(|error| {
        classify_wasmtime_error(GenerationPhase::GuestExecution, error, cancellation)
    })?;
    if args_ptr == 0 && args_len != 0 {
        return Err(incompatible(
            GenerationPhase::GuestExecution,
            "spec42_alloc returned a null pointer",
        ));
    }
    memory
        .write(&mut *store, args_ptr as usize, &args_bytes)
        .map_err(|error| incompatible(GenerationPhase::GuestExecution, error.to_string()))?;
    let packed = generate
        .call(&mut *store, (args_ptr, args_len))
        .map_err(|error| {
            classify_wasmtime_error(GenerationPhase::GuestExecution, error, cancellation)
        })? as u64;
    let output_ptr = (packed & u32::MAX as u64) as u32 as usize;
    let output_len = (packed >> 32) as usize;
    if output_len > max_artifact_result_bytes(artifact_limits) {
        return Err(GeneratorHostError {
            category: GeneratorFailureCategory::OutputPolicy,
            phase: GenerationPhase::ArtifactValidation,
            message: "generator result exceeds the configured artifact limits".to_owned(),
        });
    }
    // Confirm the range is really in guest memory before allocating a host buffer to match
    // it: the length is guest-supplied, and a bad one should cost an error, not 128 MiB.
    let available = memory.data_size(&mut *store);
    if output_ptr
        .checked_add(output_len)
        .is_none_or(|end| end > available)
    {
        return Err(incompatible(
            GenerationPhase::GuestExecution,
            "generator result lies outside guest memory",
        ));
    }
    let mut output = vec![0; output_len];
    memory
        .read(&mut *store, output_ptr, &mut output)
        .map_err(|error| incompatible(GenerationPhase::GuestExecution, error.to_string()))?;
    // The guest's result buffer is deliberately not freed: the store is dropped immediately
    // below, so a `spec42_dealloc` call would only give a completed run another chance to
    // trap. That is why the export is not part of the ABI.
    validate_artifact_result_header(&output, artifact_limits.max_files)?;
    let (result, remaining): (Result<Vec<protocol::Artifact>, String>, _) =
        postcard::take_from_bytes(&output).map_err(|error| {
            incompatible(
                GenerationPhase::GuestExecution,
                format!("generator returned an invalid result: {error}"),
            )
        })?;
    if !remaining.is_empty() {
        return Err(incompatible(
            GenerationPhase::GuestExecution,
            "generator result contains trailing bytes",
        ));
    }
    let returned = result.map_err(|message| GeneratorHostError {
        category: GeneratorFailureCategory::GeneratorError,
        phase: GenerationPhase::GuestExecution,
        message,
    })?;
    validate_returned_artifacts(returned, artifact_limits)
}

fn max_artifact_result_bytes(limits: ArtifactLimits) -> usize {
    limits
        .max_total_bytes
        .saturating_add(
            limits
                .max_files
                .saturating_mul(MAX_ARTIFACT_PATH_BYTES + MAX_POSTCARD_ARTIFACT_OVERHEAD_BYTES),
        )
        .saturating_add(MAX_POSTCARD_RESULT_OVERHEAD_BYTES)
        .max(MIN_ACCEPTED_RESULT_BYTES)
        .min(i32::MAX as usize)
}

fn validate_artifact_result_header(
    output: &[u8],
    max_files: usize,
) -> Result<(), GeneratorHostError> {
    let Ok((variant, remaining)) = postcard::take_from_bytes::<u32>(output) else {
        return Ok(());
    };
    if variant != 0 {
        return Ok(());
    }
    let Ok((count, _)) = postcard::take_from_bytes::<u32>(remaining) else {
        return Ok(());
    };
    let count = count as usize;
    if count > max_files {
        return Err(GeneratorHostError {
            category: GeneratorFailureCategory::OutputPolicy,
            phase: GenerationPhase::ArtifactValidation,
            message: format!("generator returned {count} files; the limit is {max_files}"),
        });
    }
    Ok(())
}

fn validate_returned_artifacts(
    returned: Vec<protocol::Artifact>,
    limits: ArtifactLimits,
) -> Result<ArtifactSet, GeneratorHostError> {
    let mut artifacts = ArtifactSet::new(limits);
    for artifact in returned {
        artifacts
            .emit(&artifact.file_path, artifact.contents)
            .map_err(|error| GeneratorHostError {
                category: GeneratorFailureCategory::OutputPolicy,
                phase: GenerationPhase::ArtifactValidation,
                message: error.to_string(),
            })?;
    }
    Ok(artifacts)
}

struct HostState {
    model: Arc<GeneratorModelView>,
    diagnostics: Vec<GeneratorDiagnostic>,
    diagnostic_bytes: usize,
    limits: MeteredLimits,
    query_count: u64,
    /// The most recent (operation, request) and its encoded response.
    ///
    /// The capacity-probe protocol has a guest call the same query twice: once to discover
    /// the size, once to receive it. Without this, the second call re-walks the model,
    /// re-hashes every element and re-serialises -- doubling the cost of every response
    /// larger than the guest's initial buffer, which for a whole-model query is all of them.
    last_response: Option<(i32, Vec<u8>, Vec<u8>)>,
    deadline: Option<Instant>,
    clock: Arc<dyn Clock>,
    cancellation: CancellationHandle,
    /// Set the first time the guest calls into the host, so an observer can tell that
    /// WebAssembly is genuinely executing rather than merely that a thread was spawned.
    entered: Arc<AtomicBool>,
}

impl HostState {
    fn queried(&mut self) {
        self.entered.store(true, Ordering::Release);
        self.query_count = self.query_count.saturating_add(1);
    }

    fn cached_response(&self, operation: i32, request: &[u8]) -> Option<Vec<u8>> {
        self.last_response
            .as_ref()
            .filter(|(cached_op, cached_request, _)| {
                *cached_op == operation && cached_request == request
            })
            .map(|(_, _, response)| response.clone())
    }

    fn remember_response(&mut self, operation: i32, request: &[u8], response: &[u8]) {
        self.last_response = Some((operation, request.to_vec(), response.to_vec()));
    }

    /// Refuses to service a host call once the run is cancelled or past its deadline.
    ///
    /// Epoch interruption only lands at a loop back-edge or function entry, so a guest whose
    /// entrypoint is a straight-line run of host calls never reaches one. Checking here
    /// bounds that shape too, and does not depend on wasmtime's check-point placement.
    fn guard(&self) -> wasmtime::Result<()> {
        if self.cancellation.is_cancelled() {
            return Err(wasmtime::Error::new(GuestInterrupt::Cancelled));
        }
        if self
            .deadline
            .is_some_and(|deadline| self.clock.now() >= deadline)
        {
            return Err(wasmtime::Error::new(GuestInterrupt::DeadlineExceeded));
        }
        Ok(())
    }
}

fn add_host_functions(linker: &mut Linker<HostState>) -> wasmtime::Result<()> {
    linker.func_wrap(
        protocol::IMPORT_MODULE,
        "query",
        |mut caller: Caller<'_, HostState>,
         operation: i32,
         request_ptr: i32,
         request_len: i32,
         response_ptr: i32,
         response_capacity: i32|
         -> wasmtime::Result<i64> {
            caller.data().guard()?;
            let request = read_guest(&mut caller, request_ptr, request_len)?;
            let response = handle_query(caller.data_mut(), operation, &request)?;
            write_guest_response(&mut caller, response_ptr, response_capacity, &response)
        },
    )?;
    linker.func_wrap(
        protocol::IMPORT_MODULE,
        "diagnostic",
        |mut caller: Caller<'_, HostState>,
         level: i32,
         message_ptr: i32,
         message_len: i32,
         element_ptr: i32,
         element_len: i32|
         -> wasmtime::Result<()> {
            caller.data().guard()?;
            let level = diagnostic_level(level)?;
            // Check the cheap caps before reading anything out of guest memory: past the
            // limit the diagnostic is discarded regardless, and the reads are not free.
            {
                let state = caller.data();
                if state.diagnostics.len() >= MAX_DIAGNOSTICS
                    || state.diagnostic_bytes >= MAX_DIAGNOSTIC_TOTAL_BYTES
                {
                    return Ok(());
                }
            }
            let message = read_guest_string(&mut caller, message_ptr, message_len)?;
            let element = if element_ptr == 0 && element_len == 0 {
                None
            } else {
                Some(read_guest_string(&mut caller, element_ptr, element_len)?)
            };
            let state = caller.data_mut();
            let element = element.filter(|handle| state.model.is_valid_handle(handle));
            let message = bounded_message(message);
            state.diagnostic_bytes = state.diagnostic_bytes.saturating_add(message.len());
            state.diagnostics.push(GeneratorDiagnostic {
                level,
                message,
                element_id: element,
            });
            Ok(())
        },
    )?;
    Ok(())
}

fn handle_query(
    state: &mut HostState,
    operation: i32,
    request: &[u8],
) -> wasmtime::Result<Vec<u8>> {
    // A capacity probe repeats the previous query verbatim; serve it from the last result
    // rather than recomputing, and do not count it as a second logical query.
    if let Some(cached) = state.cached_response(operation, request) {
        return Ok(cached);
    }
    state.queried();
    // Resolve the code once; an operation this ABI does not define is a contract breach, not
    // a fallthrough arm in the dispatch below.
    let operation = protocol::Operation::try_from_code(operation)
        .map_err(|unknown| AbiViolation::error(unknown.to_string()))?;
    let response = match operation {
        protocol::Operation::Info => encode_result(Ok(protocol::ModelInfo {
            model_digest: state.model.model_digest(),
            spec42_version: state.model.spec42_version().to_owned(),
            semantic_api_version: state.model.semantic_api_version().to_owned(),
        })),
        protocol::Operation::Roots => encode_result(
            state
                .model
                .roots()
                .map(|values| values.into_iter().map(summary).collect::<Vec<_>>())
                .map_err(|error| error.to_string()),
        ),
        protocol::Operation::Find => {
            let metaclass = decode_for::<protocol::query::Find>(request)?;
            encode_result(
                state
                    .model
                    .find(metaclass.as_deref())
                    .map(|values| values.into_iter().map(summary).collect::<Vec<_>>())
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::Children => {
            let owner = decode_for::<protocol::query::Children>(request)?;
            encode_result(
                state
                    .model
                    .children(&owner)
                    .map(|values| values.into_iter().map(summary).collect::<Vec<_>>())
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::Element => {
            let handle = decode_for::<protocol::query::Element>(request)?;
            encode_result(
                state
                    .model
                    .element(&handle)
                    .map(detail)
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::TypedBy => {
            let feature = decode_for::<protocol::query::TypedBy>(request)?;
            encode_result(
                state
                    .model
                    .typed_by(&feature)
                    .map(|value| value.map(summary))
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::RequirementTyping => {
            let usage = decode_for::<protocol::query::RequirementTyping>(request)?;
            encode_result(
                state
                    .model
                    .requirement_usage_typing(&usage)
                    .map(requirement_usage_typing)
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::SatisfyRelationships => encode_result(
            state
                .model
                .satisfy_relationships()
                .map(|values| {
                    values
                        .into_iter()
                        .map(satisfy_relationship)
                        .collect::<Vec<_>>()
                })
                .map_err(|error| error.to_string()),
        ),
        protocol::Operation::Relationships => {
            let element = decode_for::<protocol::query::Relationships>(request)?;
            encode_result(
                state
                    .model
                    .relationships(&element)
                    .map(|values| values.into_iter().map(relationship).collect::<Vec<_>>())
                    .map_err(|error| error.to_string()),
            )
        }
        protocol::Operation::EffectiveFeatures => {
            let element = decode_for::<protocol::query::EffectiveFeatures>(request)?;
            encode_result(
                state
                    .model
                    .effective_features(&element)
                    .map(|values| values.into_iter().map(summary).collect::<Vec<_>>())
                    .map_err(|error| error.to_string()),
            )
        }
    }?;
    state.remember_response(operation.code(), request, &response);
    Ok(response)
}

/// Decodes a request as the type the ABI declares for that operation.
///
/// Going through the marker type is what keeps the host's choice of payload type tied to the
/// operation code: picking one independently is no longer expressible.
fn decode_for<Q: protocol::Query>(bytes: &[u8]) -> wasmtime::Result<Q::Request> {
    postcard::from_bytes(bytes)
        .map_err(|error| AbiViolation::error(format!("invalid Spec42 query request: {error}")))
}

fn encode_result<T: Serialize>(result: Result<T, String>) -> wasmtime::Result<Vec<u8>> {
    postcard::to_allocvec(&result)
        .map_err(|error| wasmtime::Error::msg(format!("failed to encode query response: {error}")))
}

fn guest_memory(caller: &mut Caller<'_, HostState>) -> wasmtime::Result<Memory> {
    caller
        .get_export("memory")
        .and_then(Extern::into_memory)
        .ok_or_else(|| AbiViolation::error("generator does not export memory"))
}

fn transfer_range(pointer: i32, length: i32) -> wasmtime::Result<(usize, usize)> {
    let pointer = usize::try_from(pointer)
        .map_err(|_| AbiViolation::error("negative guest memory pointer"))?;
    let length =
        usize::try_from(length).map_err(|_| AbiViolation::error("negative guest memory length"))?;
    if length > MAX_QUERY_TRANSFER_BYTES {
        return Err(AbiViolation::error("guest transfer exceeds the ABI limit"));
    }
    Ok((pointer, length))
}

fn read_guest(
    caller: &mut Caller<'_, HostState>,
    pointer: i32,
    length: i32,
) -> wasmtime::Result<Vec<u8>> {
    let (pointer, length) = transfer_range(pointer, length)?;
    let memory = guest_memory(caller)?;
    let mut bytes = vec![0; length];
    memory
        .read(caller, pointer, &mut bytes)
        .map_err(|error| AbiViolation::error(error.to_string()))?;
    Ok(bytes)
}

fn read_guest_string(
    caller: &mut Caller<'_, HostState>,
    pointer: i32,
    length: i32,
) -> wasmtime::Result<String> {
    String::from_utf8(read_guest(caller, pointer, length)?)
        .map_err(|error| AbiViolation::error(format!("guest string is not UTF-8: {error}")))
}

fn write_guest_response(
    caller: &mut Caller<'_, HostState>,
    pointer: i32,
    capacity: i32,
    bytes: &[u8],
) -> wasmtime::Result<i64> {
    let (pointer, capacity) = transfer_range(pointer, capacity)?;
    if bytes.len() > MAX_QUERY_TRANSFER_BYTES {
        return Err(AbiViolation::error("host response exceeds the ABI limit"));
    }
    if bytes.len() > capacity {
        return Ok(-(bytes.len() as i64));
    }
    let memory = guest_memory(caller)?;
    memory
        .write(caller, pointer, bytes)
        .map_err(|error| AbiViolation::error(error.to_string()))?;
    Ok(bytes.len() as i64)
}

fn summary(value: ApiElementSummary) -> protocol::ElementSummary {
    protocol::ElementSummary {
        handle: value.handle,
        semantic_id: value.semantic_id,
        metaclass: value.metaclass,
        name: value.name,
        qualified_name: value.qualified_name,
        library_element: value.library_element,
    }
}

fn multiplicity(value: ApiMultiplicity) -> protocol::Multiplicity {
    protocol::Multiplicity {
        lower: value.lower,
        upper: value.upper,
        ordered: value.ordered,
        unique: value.unique,
        implied: value.implied,
    }
}

fn detail(value: ApiElementDetail) -> protocol::ElementDetail {
    protocol::ElementDetail {
        summary: summary(value.summary),
        owner: value.owner.map(summary),
        declared_name: value.declared_name,
        effective_name: value.effective_name,
        source_uri: value.source_uri,
        source_range: protocol::SourceRange {
            start_line: value.source_range.start_line,
            start_character: value.source_range.start_character,
            end_line: value.source_range.end_line,
            end_character: value.source_range.end_character,
        },
        definition: value.definition,
        documentation: value.documentation,
        short_name: value.short_name,
        direction: value.direction,
        derived: value.derived,
        constant: value.constant,
        abstract_flag: value.abstract_,
        variation: value.variation,
        individual: value.individual,
        conjugated: value.conjugated,
        composite: value.composite,
        reference: value.reference,
        end: value.end,
        ordered: value.ordered,
        unique: value.unique,
        multiplicity: value.multiplicity.map(multiplicity),
        evaluated_value: value.evaluated_value,
    }
}

fn relationship(value: RelationshipSummary) -> protocol::Relationship {
    protocol::Relationship {
        kind: value.kind,
        source: summary(value.source),
        target: summary(value.target),
        implied: value.implied,
    }
}

fn requirement_usage_typing(
    value: RequirementUsageTypingSummary,
) -> protocol::RequirementUsageTyping {
    use protocol::RequirementUsageTyping as Wire;
    match value {
        RequirementUsageTypingSummary::Resolved {
            definition,
            provenance,
        } => Wire::Resolved {
            definition: summary(definition),
            provenance: match provenance {
                TypingProvenanceSummary::Authored => protocol::TypingProvenance::Authored,
                TypingProvenanceSummary::Implied => protocol::TypingProvenance::Implied,
            },
        },
        RequirementUsageTypingSummary::RecoveredResolved {
            definition,
            provenance,
        } => Wire::RecoveredResolved {
            definition: summary(definition),
            provenance: match provenance {
                TypingProvenanceSummary::Authored => protocol::TypingProvenance::Authored,
                TypingProvenanceSummary::Implied => protocol::TypingProvenance::Implied,
            },
        },
        RequirementUsageTypingSummary::RecoveredMissing => Wire::RecoveredMissing,
        RequirementUsageTypingSummary::RecoveredUnresolved => Wire::RecoveredUnresolved,
        RequirementUsageTypingSummary::RecoveredAmbiguous { candidates } => {
            Wire::RecoveredAmbiguous {
                candidates: candidates.into_iter().map(summary).collect(),
            }
        }
        RequirementUsageTypingSummary::RecoveredUnsupported => Wire::RecoveredUnsupported,
        RequirementUsageTypingSummary::Missing => Wire::Missing,
        RequirementUsageTypingSummary::Unresolved => Wire::Unresolved,
        RequirementUsageTypingSummary::Ambiguous { candidates } => Wire::Ambiguous {
            candidates: candidates.into_iter().map(summary).collect(),
        },
        RequirementUsageTypingSummary::Unsupported => Wire::Unsupported,
        RequirementUsageTypingSummary::Recovery => Wire::Recovery,
        RequirementUsageTypingSummary::Incomplete => Wire::Incomplete,
    }
}

fn satisfy_endpoint(value: SatisfyEndpointSummary) -> protocol::SatisfyEndpoint {
    match value {
        SatisfyEndpointSummary::Resolved(value) => {
            protocol::SatisfyEndpoint::Resolved(summary(value))
        }
        SatisfyEndpointSummary::Ambiguous(values) => {
            protocol::SatisfyEndpoint::Ambiguous(values.into_iter().map(summary).collect())
        }
        SatisfyEndpointSummary::Unresolved => protocol::SatisfyEndpoint::Unresolved,
        SatisfyEndpointSummary::Unsupported => protocol::SatisfyEndpoint::Unsupported,
    }
}

fn satisfy_relationship(value: SatisfyRelationshipSummary) -> protocol::SatisfyRelationship {
    protocol::SatisfyRelationship {
        semantic_id: value.semantic_id,
        requirement: satisfy_endpoint(value.requirement),
        satisfying_element: satisfy_endpoint(value.satisfying_element),
        polarity: match value.polarity {
            SatisfyPolaritySummary::Satisfied => protocol::SatisfyPolarity::Satisfied,
            SatisfyPolaritySummary::NotSatisfied => protocol::SatisfyPolarity::NotSatisfied,
        },
        provenance: match value.provenance {
            TypingProvenanceSummary::Authored => protocol::RelationshipProvenance::Authored,
            TypingProvenanceSummary::Implied => protocol::RelationshipProvenance::Implied,
        },
        recovered: value.recovered,
    }
}

fn diagnostic_level(level: i32) -> wasmtime::Result<GeneratorDiagnosticLevel> {
    let level = protocol::Level::try_from_code(level)
        .map_err(|unknown| AbiViolation::error(unknown.to_string()))?;
    Ok(match level {
        protocol::Level::Debug => GeneratorDiagnosticLevel::Debug,
        protocol::Level::Info => GeneratorDiagnosticLevel::Info,
        protocol::Level::Warning => GeneratorDiagnosticLevel::Warning,
        protocol::Level::Error => GeneratorDiagnosticLevel::Error,
    })
}

fn digest(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

fn bounded_message(mut message: String) -> String {
    const MAX_MESSAGE_BYTES: usize = 64 * 1024;
    if message.len() <= MAX_MESSAGE_BYTES {
        return message;
    }
    let mut boundary = MAX_MESSAGE_BYTES;
    while !message.is_char_boundary(boundary) {
        boundary -= 1;
    }
    message.truncate(boundary);
    message
}

fn incompatible(phase: GenerationPhase, message: impl Into<String>) -> GeneratorHostError {
    GeneratorHostError {
        category: GeneratorFailureCategory::ApiIncompatible,
        phase,
        message: message.into(),
    }
}

/// Classifies a failure from Wasmtime by inspecting the error, not its rendered text.
///
/// Wasmtime attaches a [`WasmBacktrace`] as the outermost context of any error raised while
/// guest code is on the stack, and `Display` for an `anyhow::Error` shows only that outermost
/// layer. So `to_string()` on a fuel exhaustion is the backtrace, not "all fuel consumed" --
/// which is why matching on message substrings classified the two most important failures
/// wrongly and discarded every message the host itself produced. Downcasting sees through the
/// context, and `root_cause` recovers the message the caller should read.
///
/// [`WasmBacktrace`]: wasmtime::WasmBacktrace
fn classify_wasmtime_error(
    phase: GenerationPhase,
    error: wasmtime::Error,
    cancellation: &CancellationHandle,
) -> GeneratorHostError {
    if cancellation.is_cancelled() {
        return GeneratorHostError {
            category: GeneratorFailureCategory::Cancelled,
            phase,
            message: "generation was cancelled".to_owned(),
        };
    }
    let message = bounded_message(error.root_cause().to_string());
    if let Some(interrupt) = error.downcast_ref::<GuestInterrupt>() {
        return GeneratorHostError {
            category: match interrupt {
                GuestInterrupt::Cancelled => GeneratorFailureCategory::Cancelled,
                GuestInterrupt::DeadlineExceeded => GeneratorFailureCategory::ResourceExhausted,
            },
            phase,
            message,
        };
    }
    if error.downcast_ref::<AbiViolation>().is_some() {
        return GeneratorHostError {
            category: GeneratorFailureCategory::ApiIncompatible,
            phase,
            message,
        };
    }
    let category = match error.downcast_ref::<Trap>() {
        // `Interrupt` is the epoch firing, which for this host means the wall-clock deadline;
        // cancellation was already handled above.
        Some(Trap::OutOfFuel | Trap::Interrupt) => GeneratorFailureCategory::ResourceExhausted,
        Some(_) => GeneratorFailureCategory::Trap,
        // Not a trap and not one of ours: a link or instantiation failure.
        None => GeneratorFailureCategory::ApiIncompatible,
    };
    GeneratorHostError {
        category,
        phase,
        message,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn non_wasm_input_is_rejected_as_a_module_validation_error() {
        let runtime = GeneratorRuntime::new().expect("runtime");
        let error = match runtime.prepare(b"not wasm") {
            Ok(_) => panic!("non-wasm input unexpectedly prepared"),
            Err(error) => error,
        };
        assert_eq!(error.category, GeneratorFailureCategory::ArtifactInvalid);
        assert_eq!(error.phase, GenerationPhase::ModuleValidation);
        assert_eq!(error.message, "not a core WebAssembly module");
    }

    #[test]
    fn missing_abi_exports_are_rejected_during_preparation() {
        let runtime = GeneratorRuntime::new().expect("runtime");
        let empty_module = b"\0asm\x01\0\0\0";
        let error = match runtime.prepare(empty_module) {
            Ok(_) => panic!("module without ABI exports unexpectedly prepared"),
            Err(error) => error,
        };
        assert_eq!(error.category, GeneratorFailureCategory::ApiIncompatible);
        assert_eq!(error.phase, GenerationPhase::ApiCompatibility);
        assert_eq!(error.message, "module does not export `memory`");
    }

    #[test]
    fn returned_artifacts_are_validated_and_sorted() {
        let artifacts = validate_returned_artifacts(
            vec![
                protocol::Artifact {
                    file_path: "z.bin".to_owned(),
                    contents: vec![0, 255],
                },
                protocol::Artifact {
                    file_path: "a/report.txt".to_owned(),
                    contents: b"report".to_vec(),
                },
            ],
            ArtifactLimits::default(),
        )
        .expect("valid returned artifacts");

        assert_eq!(
            artifacts
                .iter()
                .map(|artifact| artifact.path.to_string())
                .collect::<Vec<_>>(),
            ["a/report.txt", "z.bin"]
        );
    }

    #[test]
    fn duplicate_returned_paths_are_output_policy_failures() {
        let error = validate_returned_artifacts(
            vec![
                protocol::Artifact {
                    file_path: "report.txt".to_owned(),
                    contents: vec![],
                },
                protocol::Artifact {
                    file_path: "report.txt".to_owned(),
                    contents: vec![],
                },
            ],
            ArtifactLimits::default(),
        )
        .expect_err("duplicate path should fail");

        assert_eq!(error.category, GeneratorFailureCategory::OutputPolicy);
        assert_eq!(error.phase, GenerationPhase::ArtifactValidation);
        assert!(error.message.contains("returned more than once"));
    }

    /// Wasmtime attaches a backtrace as the outermost context whenever guest code is on the
    /// stack, so every classification has to survive that wrapping. Each case is asserted
    /// both bare and contexted: the contexted form is what production actually sees.
    fn classify(error: wasmtime::Error) -> (GeneratorFailureCategory, String) {
        let cancellation = CancellationHandle::new();
        let bare = classify_wasmtime_error(GenerationPhase::GuestExecution, error, &cancellation);
        (bare.category, bare.message)
    }

    fn classify_with_backtrace(error: wasmtime::Error) -> (GeneratorFailureCategory, String) {
        let contexted = error.context("error while executing at wasm backtrace:\n  0: 0x2f");
        classify(contexted)
    }

    #[test]
    fn fuel_exhaustion_is_resource_exhausted_even_behind_a_backtrace() {
        for classified in [
            classify(wasmtime::Error::new(Trap::OutOfFuel)),
            classify_with_backtrace(wasmtime::Error::new(Trap::OutOfFuel)),
        ] {
            assert_eq!(classified.0, GeneratorFailureCategory::ResourceExhausted);
            assert!(
                classified.1.contains("fuel"),
                "message lost the cause: {}",
                classified.1
            );
        }
    }

    #[test]
    fn epoch_interruption_is_resource_exhausted_not_incompatibility() {
        assert_eq!(
            classify_with_backtrace(wasmtime::Error::new(Trap::Interrupt)).0,
            GeneratorFailureCategory::ResourceExhausted
        );
    }

    #[test]
    fn guest_traps_stay_traps_and_keep_their_reason() {
        let (category, message) =
            classify_with_backtrace(wasmtime::Error::new(Trap::MemoryOutOfBounds));
        assert_eq!(category, GeneratorFailureCategory::Trap);
        assert_eq!(message, "wasm trap: out of bounds memory access");
    }

    #[test]
    fn abi_violations_report_what_the_guest_got_wrong() {
        let (category, message) =
            classify_with_backtrace(AbiViolation::error("unknown Spec42 query operation 8"));
        assert_eq!(category, GeneratorFailureCategory::ApiIncompatible);
        assert_eq!(message, "unknown Spec42 query operation 8");
    }

    #[test]
    fn deadline_is_resource_exhausted_and_cancellation_is_cancelled() {
        assert_eq!(
            classify_with_backtrace(wasmtime::Error::new(GuestInterrupt::DeadlineExceeded)).0,
            GeneratorFailureCategory::ResourceExhausted
        );

        let cancellation = CancellationHandle::new();
        cancellation.cancel();
        let cancelled = classify_wasmtime_error(
            GenerationPhase::GuestExecution,
            wasmtime::Error::new(Trap::Interrupt),
            &cancellation,
        );
        assert_eq!(cancelled.category, GeneratorFailureCategory::Cancelled);
    }

    #[test]
    fn returned_artifact_count_is_bounded_before_deserialization() {
        let encoded = postcard::to_allocvec(&Ok::<_, String>(vec![
            protocol::Artifact {
                file_path: "a".to_owned(),
                contents: vec![],
            },
            protocol::Artifact {
                file_path: "b".to_owned(),
                contents: vec![],
            },
        ]))
        .expect("encode result");

        let error = validate_artifact_result_header(&encoded, 1)
            .expect_err("artifact count over the limit should fail");
        assert_eq!(error.category, GeneratorFailureCategory::OutputPolicy);
        assert_eq!(error.phase, GenerationPhase::ArtifactValidation);
        assert_eq!(error.message, "generator returned 2 files; the limit is 1");
    }
}
