[package]
name = "spec42-sysml-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "sysml_v2_parser"

[dependencies]
parser-legacy = { package = "sysml-v2-parser", version = "0.54.0", features = ["serde"] }
parser-next = { package = "sysml-v2-parser", git = "https://github.com/lukewilliamboswell/sysml-v2-parser.git", rev = "204ca48000c452970beb7568d84e0ac80898a767", features = ["serde"] }
