[package]
name = "spec42-sysml-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "sysml_v2_parser"

[dependencies]
parser-next = { package = "sysml-v2-parser", git = "https://github.com/lukewilliamboswell/sysml-v2-parser.git", rev = "ec47463f86829bc7caebd44b8ad7db6eea677691", features = ["serde"] }
