//! The transaction planner: a pure function from observed state to an ordered plan.
//!
//! ```text
//! existing tree + ownership manifest + generated artifacts + mode
//!     -> ordered plan, or a policy error
//! ```
//!
//! Nothing here touches the filesystem. The caller observes the tree once and hands the
//! observation in, which makes every ownership and conflict rule a table test rather than
//! something that needs a temporary directory and a particular platform to exercise.
//!
//! The executor that applies a plan lives in [`super::apply`].

use std::collections::BTreeMap;

use generator_api::ArtifactPath;

/// What the planner found at one artifact's location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Existing {
    /// Nothing there.
    Absent,
    /// A regular file with these bytes.
    File { content: Vec<u8> },
    /// A directory, symlink, socket — anything a generated file cannot simply replace.
    NotAFile,
}

/// How the caller wants the plan applied.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Write the plan.
    Commit,
    /// Report what would happen, writing nothing.
    DryRun,
    /// Compare only; any difference is a failure exit rather than a write.
    Check,
}

/// Everything the planner needs, gathered by the caller in one pass over the tree.
#[derive(Debug, Clone, Default)]
pub struct Observation {
    /// State at each artifact's destination.
    pub existing: BTreeMap<ArtifactPath, Existing>,
    /// Path to content hash, from the previous run's manifest.
    pub owned: BTreeMap<String, String>,
}

/// What will happen to one path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Operation {
    Create,
    Change,
    Unchanged,
    /// Exists, unowned, and the generated bytes happen to match.
    ///
    /// Writing would change nothing, but recording it as owned would license a future
    /// overwrite of a file the generator never created. Treated as a conflict.
    Adopt,
    Conflict,
}

impl Operation {
    /// Whether this operation blocks a commit without `--force`.
    pub fn blocks(self) -> bool {
        matches!(self, Self::Conflict | Self::Adopt)
    }

    /// Whether this operation represents a difference for `--check`.
    pub fn differs(self) -> bool {
        matches!(self, Self::Create | Self::Change | Self::Conflict)
    }
}

/// The ordered plan.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Plan {
    /// Paths in deterministic order with their operation.
    pub steps: Vec<(ArtifactPath, Operation)>,
}

impl Plan {
    pub fn blocked(&self) -> Vec<&ArtifactPath> {
        self.steps
            .iter()
            .filter(|(_, operation)| operation.blocks())
            .map(|(path, _)| path)
            .collect()
    }

    pub fn has_differences(&self) -> bool {
        self.steps.iter().any(|(_, operation)| operation.differs())
    }

    pub fn paths_with(&self, wanted: Operation) -> Vec<String> {
        self.steps
            .iter()
            .filter(|(_, operation)| *operation == wanted)
            .map(|(path, _)| path.to_string())
            .collect()
    }
}

/// Plans the transaction. Deterministic, and a pure function of its arguments.
pub fn plan(
    artifacts: &[(ArtifactPath, Vec<u8>)],
    observation: &Observation,
    force: bool,
    digest: &dyn Fn(&[u8]) -> String,
) -> Plan {
    let mut steps = Vec::with_capacity(artifacts.len());
    for (path, content) in artifacts {
        let existing = observation
            .existing
            .get(path)
            .cloned()
            .unwrap_or(Existing::Absent);

        let operation = match existing {
            Existing::Absent => Operation::Create,
            // A directory or symlink where a file must go. `--force` may replace it, but it
            // is never a silent overwrite.
            Existing::NotAFile => {
                if force {
                    Operation::Change
                } else {
                    Operation::Conflict
                }
            }
            Existing::File { content: current } => {
                let owned = observation
                    .owned
                    .get(path.as_str())
                    .is_some_and(|recorded| *recorded == digest(&current));
                if current == *content {
                    if owned || force {
                        Operation::Unchanged
                    } else {
                        Operation::Adopt
                    }
                } else if owned || force {
                    Operation::Change
                } else {
                    Operation::Conflict
                }
            }
        };
        steps.push((path.clone(), operation));
    }
    steps.sort();
    Plan { steps }
}

/// The manifest to write, carrying forward ownership of files this run did not regenerate.
///
/// Rebuilding from the current artifacts alone would forfeit ownership of anything the
/// generator stopped emitting, and a run producing nothing would forfeit all of it.
pub fn retained_ownership(
    artifacts: &[(ArtifactPath, Vec<u8>)],
    previous: &BTreeMap<String, String>,
    digest: &dyn Fn(&[u8]) -> String,
) -> BTreeMap<String, String> {
    let mut owned = previous.clone();
    for (path, content) in artifacts {
        owned.insert(path.to_string(), digest(content));
    }
    owned
}

#[cfg(test)]
mod tests {
    use super::*;

    fn path(raw: &str) -> ArtifactPath {
        ArtifactPath::parse(raw).expect(raw)
    }

    /// A stand-in digest: readable in failure output and enough to distinguish contents.
    fn fake_digest(bytes: &[u8]) -> String {
        format!("d{}", bytes.len())
    }

    fn observe(entries: &[(&str, Existing)], owned: &[(&str, &str)]) -> Observation {
        Observation {
            existing: entries
                .iter()
                .map(|(name, state)| (path(name), state.clone()))
                .collect(),
            owned: owned
                .iter()
                .map(|(name, hash)| ((*name).to_owned(), (*hash).to_owned()))
                .collect(),
        }
    }

    /// The full decision table: every combination of what is on disk, whether we own it,
    /// whether the bytes match, and whether `--force` was given.
    #[test]
    fn the_ownership_decision_table_is_exhaustive() {
        let generated = b"generated".to_vec();
        let cases: &[(&str, Existing, bool, bool, Operation)] = &[
            // (label, on disk, owned, force, expected)
            ("absent", Existing::Absent, false, false, Operation::Create),
            (
                "absent, forced",
                Existing::Absent,
                false,
                true,
                Operation::Create,
            ),
            (
                "same bytes, unowned",
                Existing::File {
                    content: b"generated".to_vec(),
                },
                false,
                false,
                Operation::Adopt,
            ),
            (
                "same bytes, unowned, forced",
                Existing::File {
                    content: b"generated".to_vec(),
                },
                false,
                true,
                Operation::Unchanged,
            ),
            (
                "same bytes, owned",
                Existing::File {
                    content: b"generated".to_vec(),
                },
                true,
                false,
                Operation::Unchanged,
            ),
            (
                "different bytes, unowned",
                Existing::File {
                    content: b"local".to_vec(),
                },
                false,
                false,
                Operation::Conflict,
            ),
            (
                "different bytes, unowned, forced",
                Existing::File {
                    content: b"local".to_vec(),
                },
                false,
                true,
                Operation::Change,
            ),
            (
                "different bytes, owned",
                Existing::File {
                    content: b"local".to_vec(),
                },
                true,
                false,
                Operation::Change,
            ),
            (
                "not a file",
                Existing::NotAFile,
                false,
                false,
                Operation::Conflict,
            ),
            (
                "not a file, owned",
                Existing::NotAFile,
                true,
                false,
                Operation::Conflict,
            ),
            (
                "not a file, forced",
                Existing::NotAFile,
                false,
                true,
                Operation::Change,
            ),
        ];

        for (label, existing, owned, force, expected) in cases {
            let owned_entries: Vec<(&str, &str)> = if *owned {
                match existing {
                    Existing::File { content } => {
                        vec![("a.txt", Box::leak(fake_digest(content).into_boxed_str()))]
                    }
                    _ => vec![("a.txt", "d0")],
                }
            } else {
                vec![]
            };
            let observation = observe(&[("a.txt", existing.clone())], &owned_entries);
            let plan = plan(
                &[(path("a.txt"), generated.clone())],
                &observation,
                *force,
                &fake_digest,
            );
            assert_eq!(
                plan.steps,
                vec![(path("a.txt"), *expected)],
                "case `{label}` planned unexpectedly"
            );
        }
    }

    #[test]
    fn a_plan_is_ordered_deterministically() {
        let artifacts = vec![
            (path("z.txt"), b"z".to_vec()),
            (path("a/b.txt"), b"b".to_vec()),
            (path("a/a.txt"), b"a".to_vec()),
        ];
        let planned = plan(&artifacts, &Observation::default(), false, &fake_digest);
        assert_eq!(
            planned
                .steps
                .iter()
                .map(|(path, _)| path.to_string())
                .collect::<Vec<_>>(),
            ["a/a.txt", "a/b.txt", "z.txt"]
        );
    }

    #[test]
    fn blocking_and_difference_are_distinct_questions() {
        let artifacts = vec![
            (path("created.txt"), b"new".to_vec()),
            (path("adopted.txt"), b"same".to_vec()),
        ];
        let observation = observe(
            &[
                ("created.txt", Existing::Absent),
                (
                    "adopted.txt",
                    Existing::File {
                        content: b"same".to_vec(),
                    },
                ),
            ],
            &[],
        );
        let planned = plan(&artifacts, &observation, false, &fake_digest);

        // An adoption blocks a commit but is not itself a byte difference; a creation is a
        // difference but only blocks if it conflicts.
        assert_eq!(planned.blocked(), vec![&path("adopted.txt")]);
        assert!(planned.has_differences());
    }

    #[test]
    fn ownership_is_carried_forward_for_files_this_run_did_not_emit() {
        let previous: BTreeMap<String, String> = [
            ("kept.txt".to_owned(), "d1".to_owned()),
            ("dropped.txt".to_owned(), "d2".to_owned()),
        ]
        .into_iter()
        .collect();
        let artifacts = vec![(path("kept.txt"), b"xx".to_vec())];

        let owned = retained_ownership(&artifacts, &previous, &fake_digest);
        assert_eq!(owned.get("dropped.txt"), Some(&"d2".to_owned()));
        assert_eq!(owned.get("kept.txt"), Some(&"d2".to_owned()));

        // A run producing nothing keeps the whole record.
        let empty = retained_ownership(&[], &previous, &fake_digest);
        assert_eq!(empty, previous);
    }
}
