use std::path::PathBuf;

use clap::{Args, Parser, Subcommand, ValueEnum};

#[derive(Debug, Clone, Parser)]
#[command(name = "spec42", version, about = "SysML v2 language server and CLI")]
pub struct Cli {
    #[arg(long = "config", global = true)]
    pub config_path: Option<PathBuf>,
    #[arg(long = "library-path", global = true)]
    pub library_paths: Vec<PathBuf>,
    #[arg(long = "stdlib-path", global = true)]
    pub stdlib_path: Option<PathBuf>,
    /// Override a managed KPAR library install path (repeatable): `--kpar-library-path domain=C:/libs/domain`.
    /// An id that isn't a registered library (domain, method, ...) registers an ad-hoc
    /// extra KPAR library instead of overriding one.
    #[arg(long = "kpar-library-path", global = true, value_name = "ID=PATH")]
    pub kpar_library_paths: Vec<String>,
    /// Disable a registered KPAR library by id (repeatable): `--disable-kpar-library domain`.
    #[arg(long = "disable-kpar-library", global = true, value_name = "ID")]
    pub disabled_kpar_libraries: Vec<String>,
    #[arg(long = "no-stdlib", global = true, default_value_t = false)]
    pub no_stdlib: bool,
    #[arg(long = "stdio", global = true, hide = true, default_value_t = false)]
    pub stdio: bool,
    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Debug, Clone, Subcommand)]
pub enum Command {
    Lsp,
    Check(CheckArgs),
    /// Scaffold a validated starter SysML v2 workspace. Existing files are never overwritten.
    Init(InitArgs),
    /// Run a sandboxed WebAssembly plugin against a resolved semantic model.
    Generate(GenerateArgs),
    Doctor(DoctorArgs),
    /// Explain a diagnostic code.
    ExplainDiagnostic(ExplainDiagnosticArgs),
    /// Compact semantic graph summary.
    ModelSummary(ModelSummaryArgs),
    Sysand {
        #[command(subcommand)]
        command: SysandCommand,
    },
    Stdlib {
        #[command(subcommand)]
        command: StdlibCommand,
    },
    /// Manage config-driven managed KPAR libraries (domain, method, and future Elan8 bundles).
    Libraries {
        #[command(subcommand)]
        command: LibrariesCommand,
    },
    Diagrams {
        #[command(subcommand)]
        command: DiagramsCommand,
    },
}

#[derive(Debug, Clone, Args)]
pub struct GenerateArgs {
    /// Core WebAssembly module implementing the Spec42 generator ABI.
    pub generator: PathBuf,
    /// SysML/KerML file or workspace directory.
    pub path: PathBuf,
    #[arg(long = "workspace-root")]
    pub workspace_root: Option<PathBuf>,
    /// Generator-owned output directory.
    #[arg(long = "output", default_value = "generated")]
    pub output: PathBuf,
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Text)]
    pub format: OutputFormat,
    /// Compare generated bytes with disk without writing; exits 15 on drift.
    #[arg(long = "check", default_value_t = false, conflicts_with = "dry_run")]
    pub check: bool,
    /// Print proposed operations without writing.
    #[arg(long = "dry-run", default_value_t = false)]
    pub dry_run: bool,
    /// Permit overwriting files not owned by the previous generation manifest.
    #[arg(long = "force", default_value_t = false)]
    pub force: bool,
    #[arg(long = "strict-diagnostics", default_value_t = false)]
    pub strict_diagnostics: bool,
    /// Ceiling on guest linear memory, to contain a runaway allocation.
    #[arg(long = "max-memory-bytes", default_value_t = 268_435_456)]
    pub max_memory_bytes: usize,
    /// Guest instruction budget. Omitted, the generator runs unmetered; supplying it also
    /// enables fuel accounting, so `fuel_consumed` appears in the report.
    #[arg(long = "max-fuel")]
    pub max_fuel: Option<u64>,
    /// Wall-clock budget. Omitted, a slow generator runs to completion.
    #[arg(long = "timeout-seconds")]
    pub timeout_seconds: Option<u64>,
    #[arg(long = "max-files", default_value_t = 1_000)]
    pub max_files: usize,
    #[arg(long = "max-file-bytes", default_value_t = 16_777_216)]
    pub max_file_bytes: usize,
    #[arg(long = "max-total-bytes", default_value_t = 134_217_728)]
    pub max_total_bytes: usize,
    /// Arguments passed verbatim to the guest after `--`.
    #[arg(last = true)]
    pub generator_args: Vec<String>,
}

#[derive(Debug, Clone, Args)]
pub struct CheckArgs {
    pub path: PathBuf,
    #[arg(long = "workspace-root")]
    pub workspace_root: Option<PathBuf>,
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Text)]
    pub format: OutputFormat,
    #[arg(long = "warnings-as-errors", default_value_t = false)]
    pub warnings_as_errors: bool,
    #[arg(long = "baseline")]
    pub baseline: Option<PathBuf>,
    #[arg(
        long = "strict-diagnostics",
        default_value_t = false,
        help = "Legacy check mode: skip semantic diagnostics after parse errors and suppress shadowed unresolved warnings"
    )]
    pub strict_diagnostics: bool,
}

#[derive(Debug, Clone, Args)]
pub struct InitArgs {
    /// New or empty directory that will contain the starter workspace.
    pub path: PathBuf,
}

#[derive(Debug, Clone, Args)]
pub struct DoctorArgs {
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Text)]
    pub format: OutputFormat,
}

#[derive(Debug, Clone, Args)]
pub struct ExplainDiagnosticArgs {
    /// Diagnostic code (for example `unresolved_type_reference`).
    #[arg(long = "code")]
    pub code: String,
    /// Optional file or directory to list matching diagnostics from validation.
    #[arg(long = "path")]
    pub path: Option<PathBuf>,
    #[arg(long = "workspace-root")]
    pub workspace_root: Option<PathBuf>,
    /// Optional 0-based line number to filter instances.
    #[arg(long = "line")]
    pub line: Option<u32>,
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Json)]
    pub format: OutputFormat,
}

fn default_max_nodes() -> usize {
    500
}

#[derive(Debug, Clone, Args)]
pub struct ModelSummaryArgs {
    pub path: PathBuf,
    #[arg(long = "workspace-root")]
    pub workspace_root: Option<PathBuf>,
    #[arg(long = "max-nodes", default_value_t = default_max_nodes())]
    pub max_nodes: usize,
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Json)]
    pub format: OutputFormat,
}

#[derive(Debug, Clone, Args)]
pub struct StdlibStatusArgs {
    #[arg(long = "version")]
    pub version: Option<String>,
    #[arg(long = "repo")]
    pub repo: Option<String>,
    #[arg(long = "content-path")]
    pub content_path: Option<String>,
}

#[derive(Debug, Clone, Subcommand)]
pub enum StdlibCommand {
    /// Show pinned vs installed standard library metadata.
    Status(StdlibStatusArgs),
    /// Print the resolved standard library directory path.
    Path(StdlibStatusArgs),
    /// Delete materialized standard-library files from the data directory (they are re-created from the embedded copy on next use).
    ClearCache,
}

#[derive(Debug, Clone, Args)]
pub struct LibrariesIdArgs {
    /// Restrict the command to a single library id (for example `domain` or `method`). Omit to target all registered libraries.
    #[arg(long = "id")]
    pub id: Option<String>,
}

#[derive(Debug, Clone, Subcommand)]
pub enum LibrariesCommand {
    /// Show pinned vs installed metadata for registered KPAR libraries.
    Status(LibrariesIdArgs),
    /// Print the resolved directory path for registered KPAR libraries.
    Path(LibrariesIdArgs),
    /// Delete materialized KPAR library files from the data directory (they are re-created from the embedded copy on next use).
    ClearCache(LibrariesIdArgs),
    /// Delete the on-disk built-library-graph cache, forcing a full rebuild on the
    /// next server start. Use this after enabling/disabling a library or changing
    /// a `--kpar-library-path` override so a stale cached graph never lingers.
    ClearGraphCache,
}

#[derive(Debug, Clone, Subcommand)]
pub enum SysandCommand {
    /// Show optional Sysand package-manager integration status.
    Status(SysandStatusArgs),
}

#[derive(Debug, Clone, Args)]
pub struct SysandStatusArgs {
    #[arg(long = "format", value_enum, default_value_t = OutputFormat::Text)]
    pub format: OutputFormat,
}

#[derive(Debug, Clone, Subcommand)]
pub enum DiagramsCommand {
    /// Export deterministic shared-view payloads for CI documentation workflows.
    Export(DiagramExportArgs),
}

#[derive(Debug, Clone, Args)]
pub struct DiagramExportArgs {
    pub path: PathBuf,
    #[arg(long = "workspace-root")]
    pub workspace_root: Option<PathBuf>,
    #[arg(long = "view", default_value = "all")]
    pub view: String,
    /// Explicit SysML view usage name (for example `gridStructure` or `RegionalGridExpansion::Views::gridStructure`).
    #[arg(long = "selected-view")]
    pub selected_view: Option<String>,
    #[arg(long = "format", value_enum, default_value_t = DiagramExportFormat::Svg)]
    pub format: DiagramExportFormat,
    #[arg(long = "output")]
    pub output: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum OutputFormat {
    Text,
    Json,
    Sarif,
    Junit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagramExportFormat {
    Svg,
    Json,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bare_invocation_keeps_lsp_compatibility() {
        let cli = Cli::parse_from(["spec42"]);
        assert!(cli.command.is_none());
    }

    #[test]
    fn stdio_flag_parses_for_legacy_editor_compatibility() {
        let cli = Cli::parse_from(["spec42", "--stdio"]);
        assert!(cli.stdio);
        assert!(cli.command.is_none());
    }

    #[test]
    fn check_command_parses_workspace_root_and_format() {
        let cli = Cli::parse_from([
            "spec42",
            "check",
            "models",
            "--workspace-root",
            "workspace",
            "--format",
            "json",
        ]);
        match cli.command {
            Some(Command::Check(args)) => {
                assert_eq!(args.path, PathBuf::from("models"));
                assert_eq!(args.workspace_root, Some(PathBuf::from("workspace")));
                assert_eq!(args.format, OutputFormat::Json);
                assert!(!args.warnings_as_errors);
                assert!(args.baseline.is_none());
            }
            other => panic!("expected check command, got {other:?}"),
        }
    }

    #[test]
    fn check_command_parses_ci_flags() {
        let cli = Cli::parse_from([
            "spec42",
            "check",
            "models",
            "--format",
            "sarif",
            "--warnings-as-errors",
            "--baseline",
            "baseline.json",
        ]);
        match cli.command {
            Some(Command::Check(args)) => {
                assert_eq!(args.format, OutputFormat::Sarif);
                assert!(args.warnings_as_errors);
                assert_eq!(args.baseline, Some(PathBuf::from("baseline.json")));
            }
            other => panic!("expected check command, got {other:?}"),
        }
    }

    #[test]
    fn init_command_requires_a_target_directory() {
        let cli = Cli::parse_from(["spec42", "init", "starter-model"]);
        match cli.command {
            Some(Command::Init(args)) => assert_eq!(args.path, PathBuf::from("starter-model")),
            other => panic!("expected init command, got {other:?}"),
        }
    }

    #[test]
    fn generate_command_parses_output_modes_limits_and_guest_args() {
        let cli = Cli::parse_from([
            "spec42",
            "generate",
            "generator.wasm",
            "models",
            "--workspace-root",
            ".",
            "--output",
            "generated",
            "--dry-run",
            "--max-files",
            "12",
            "--",
            "target=rust",
            "namespace=vehicle",
        ]);
        match cli.command {
            Some(Command::Generate(args)) => {
                assert_eq!(args.generator, PathBuf::from("generator.wasm"));
                assert_eq!(args.path, PathBuf::from("models"));
                assert_eq!(args.output, PathBuf::from("generated"));
                assert!(args.dry_run);
                assert_eq!(args.max_files, 12);
                assert_eq!(args.generator_args, ["target=rust", "namespace=vehicle"]);
            }
            other => panic!("expected generate command, got {other:?}"),
        }
    }

    #[test]
    fn generate_command_defaults_output_to_generated_directory() {
        let cli = Cli::parse_from(["spec42", "generate", "generator.wasm", "model.sysml"]);
        match cli.command {
            Some(Command::Generate(args)) => {
                assert_eq!(args.output, PathBuf::from("generated"));
            }
            other => panic!("expected generate command, got {other:?}"),
        }
    }

    #[test]
    fn sysand_status_command_parses() {
        let cli = Cli::parse_from(["spec42", "sysand", "status", "--format", "json"]);
        match cli.command {
            Some(Command::Sysand {
                command: SysandCommand::Status(args),
            }) => assert_eq!(args.format, OutputFormat::Json),
            other => panic!("expected sysand status command, got {other:?}"),
        }
    }

    #[test]
    fn explain_diagnostic_command_parses() {
        let cli = Cli::parse_from([
            "spec42",
            "explain-diagnostic",
            "--code",
            "unresolved_type_reference",
            "--path",
            "model.sysml",
            "--format",
            "json",
        ]);
        match cli.command {
            Some(Command::ExplainDiagnostic(args)) => {
                assert_eq!(args.code, "unresolved_type_reference");
                assert_eq!(args.path, Some(PathBuf::from("model.sysml")));
                assert_eq!(args.format, OutputFormat::Json);
            }
            other => panic!("expected explain-diagnostic command, got {other:?}"),
        }
    }

    #[test]
    fn model_summary_command_parses() {
        let cli = Cli::parse_from([
            "spec42",
            "model-summary",
            "models",
            "--workspace-root",
            "workspace",
            "--max-nodes",
            "1",
            "--format",
            "json",
        ]);
        match cli.command {
            Some(Command::ModelSummary(args)) => {
                assert_eq!(args.path, PathBuf::from("models"));
                assert_eq!(args.workspace_root, Some(PathBuf::from("workspace")));
                assert_eq!(args.max_nodes, 1);
                assert_eq!(args.format, OutputFormat::Json);
            }
            other => panic!("expected model-summary command, got {other:?}"),
        }
    }

    #[test]
    fn kpar_library_path_flag_parses_repeatable_id_equals_path() {
        let cli = Cli::parse_from([
            "spec42",
            "--kpar-library-path",
            "domain=C:/libs/domain",
            "--kpar-library-path",
            "method=C:/libs/method",
        ]);
        assert_eq!(
            cli.kpar_library_paths,
            vec![
                "domain=C:/libs/domain".to_string(),
                "method=C:/libs/method".to_string(),
            ]
        );
    }

    #[test]
    fn disable_kpar_library_flag_parses_repeatable_id() {
        let cli = Cli::parse_from([
            "spec42",
            "--disable-kpar-library",
            "domain",
            "--disable-kpar-library",
            "method",
        ]);
        assert_eq!(
            cli.disabled_kpar_libraries,
            vec!["domain".to_string(), "method".to_string()]
        );
    }

    #[test]
    fn libraries_status_command_parses_optional_id() {
        let cli = Cli::parse_from(["spec42", "libraries", "status", "--id", "domain"]);
        match cli.command {
            Some(Command::Libraries {
                command: LibrariesCommand::Status(args),
            }) => assert_eq!(args.id.as_deref(), Some("domain")),
            other => panic!("expected libraries status command, got {other:?}"),
        }
    }

    #[test]
    fn libraries_path_command_parses_without_id() {
        let cli = Cli::parse_from(["spec42", "libraries", "path"]);
        match cli.command {
            Some(Command::Libraries {
                command: LibrariesCommand::Path(args),
            }) => assert!(args.id.is_none()),
            other => panic!("expected libraries path command, got {other:?}"),
        }
    }

    #[test]
    fn libraries_clear_cache_command_parses_with_id() {
        let cli = Cli::parse_from(["spec42", "libraries", "clear-cache", "--id", "method"]);
        match cli.command {
            Some(Command::Libraries {
                command: LibrariesCommand::ClearCache(args),
            }) => assert_eq!(args.id.as_deref(), Some("method")),
            other => panic!("expected libraries clear-cache command, got {other:?}"),
        }
    }

    #[test]
    fn libraries_clear_graph_cache_command_parses() {
        let cli = Cli::parse_from(["spec42", "libraries", "clear-graph-cache"]);
        match cli.command {
            Some(Command::Libraries {
                command: LibrariesCommand::ClearGraphCache,
            }) => {}
            other => panic!("expected libraries clear-graph-cache command, got {other:?}"),
        }
    }

    #[test]
    fn diagrams_export_command_parses() {
        let cli = Cli::parse_from([
            "spec42",
            "diagrams",
            "export",
            "models",
            "--view",
            "general-view",
            "--selected-view",
            "gridStructure",
            "--format",
            "json",
            "--output",
            "out",
        ]);
        match cli.command {
            Some(Command::Diagrams {
                command: DiagramsCommand::Export(args),
            }) => {
                assert_eq!(args.path, PathBuf::from("models"));
                assert_eq!(args.view, "general-view");
                assert_eq!(args.selected_view.as_deref(), Some("gridStructure"));
                assert_eq!(args.format, DiagramExportFormat::Json);
                assert_eq!(args.output, PathBuf::from("out"));
            }
            other => panic!("expected diagrams export command, got {other:?}"),
        }
    }
}
